version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options:
      - nosniff
    Access-Control-Allow-Origin:
      - '*'
    Access-Control-Allow-Methods:
      - HEAD
      - GET
      - OPTIONS
      - DELETE
    Access-Control-Allow-Headers:
      - Authorization
      - Accept
      - Cache-Control
auth:
  htpasswd:
    realm: Docker Registry
    path: /var/lib/registry/auth/htpasswd
