name: üèóÔ∏è Build & Push Portfolio

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: production
        type: choice
        options:
          - staging
          - production

  push:
    branches:
      - master
      - develop
    paths:
      - saas/portfolio/**

env:
  IMAGE_NAME: portfolio

jobs:
  build:
    name: Build & Push Portfolio
    runs-on: ubuntu-latest

    env:
      REGISTRY_HOST: registry.freijstack.com
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USER_PROD }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./saas/portfolio
          file: ./saas/portfolio/Dockerfile
          push: true
          tags: |
            registry.freijstack.com/portfolio:latest
            registry.freijstack.com/portfolio:${{ github.sha }}
